version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/aetherflow
      - JWT_SECRET=dev_jwt_secret
      - JWT_EXPIRES_IN=90d
      - JWT_COOKIE_EXPIRES_IN=90
      - CORS_ORIGIN=http://localhost:5175
    depends_on:
      - mongo
    command: npm run dev
    restart: unless-stopped

  mongo:
    image: daocloud.io/library/mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 